name: 'shopify_source_integration_tests'
version: '0.5.1'
profile: 'integration_tests'
config-version: 2

vars:
  shopify_source:
    customer_source:          "{% if var('generating_docs','no') == 'yes' %}{{ source('shopify','customer') }}{% else %}{{ ref('shopify_customer_data') }}{% endif %}"
    order_line_refund_source: "{% if var('generating_docs','no') == 'yes' %}{{ source('shopify','order_line_refund') }}{% else %}{{ ref('shopify_order_line_refund_data') }}{% endif %}"
    order_line_source:        "{% if var('generating_docs','no') == 'yes' %}{{ source('shopify','order_line') }}{% else %}{{ ref('shopify_order_line_data') }}{% endif %}"
    order_source:             "{% if var('generating_docs','no') == 'yes' %}{{ source('shopify','order') }}{% else %}{{ ref('shopify_order_data') }}{% endif %}"
    product_source:           "{% if var('generating_docs','no') == 'yes' %}{{ source('shopify','product') }}{% else %}{{ ref('shopify_product_data') }}{% endif %}"
    order_adjustment_source:  "{% if var('generating_docs','no') == 'yes' %}{{ source('shopify','order_adjustment') }}{% else %}{{ ref('shopify_order_adjustment_data') }}{% endif %}"
    product_variant_source:   "{% if var('generating_docs','no') == 'yes' %}{{ source('shopify','product_variant') }}{% else %}{{ ref('shopify_product_variant_data') }}{% endif %}"
    refund_source:            "{% if var('generating_docs','no') == 'yes' %}{{ source('shopify','refund') }}{% else %}{{ ref('shopify_refund_data') }}{% endif %}"
    transaction_source:       "{% if var('generating_docs','no') == 'yes' %}{{ source('shopify','transaction') }}{% else %}{{ ref('shopify_transaction_data') }}{% endif %}"
    shopify_schema:           shopify_source_integration_tests

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']

seeds:
  shopify_source_integration_tests:
    +quote_columns: "{{ true if target.type in ('redshift', 'postgres') else false }}"
    shopify_customer_data:
      +column_types:
        created_at: timestamp
        updated_at: timestamp
        _fivetran_synced: timestamp
        id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        default_address_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
    shopify_order_data:
      +column_types:
        created_at: timestamp
        updated_at: timestamp
        processed_at: timestamp
        cancelled_at: timestamp
        _fivetran_synced: timestamp
        id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        customer_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        location_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        user_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
    shopify_order_line_data:
      +column_types:
        _fivetran_synced: timestamp
        order_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        product_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        variant_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
    shopify_order_line_refund_data:
      +column_types:
        _fivetran_synced: timestamp
        id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        location_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        refund_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        order_line_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
    shopify_product_data:
      +column_types:
        created_at: timestamp
        updated_at: timestamp
        published_at: timestamp
        _fivetran_synced: timestamp
        id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
    shopify_order_adjustment_data:
      +column_types:
        id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        order_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        refund_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
    shopify_product_variant_data:
      +column_types:
        id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        product_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        inventory_item_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
    shopify_transaction_data:
      +column_types:
        id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        order_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        refund_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
    shopify_refund_data:
      +column_types:
        id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        order_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        user_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"

